#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/gemma/modular_gemma.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_gemma.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2024 Google Inc. HuggingFace Inc. team. All rights reserved.
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from typing import Callable, Optional, Union

import torch
from torch import nn

# ---------------------------------------------------------------------------
# VENDORED into pi05-infer. This file was `transformers/models/gemma/modeling_gemma.py`
# and is now `pi05_infer/gemma/modeling_gemma.py`, so the `...`-relative imports
# below became absolute `transformers.*` imports. NOTHING ELSE about them changed:
# every symbol here is the *unmodified* transformers symbol, imported from the
# installed transformers rather than re-vendored. Only the five classes this file
# actually modifies (GemmaRMSNorm / GemmaMLP / GemmaAttention / GemmaDecoderLayer /
# GemmaModel) plus `rlinf_fused_denoise` live in this package.
# ---------------------------------------------------------------------------
from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.masking_utils import create_causal_mask
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_layers import GradientCheckpointingLayer
from transformers.modeling_outputs import (
    BaseModelOutputWithPast,
    CausalLMOutputWithPast,
    SequenceClassifierOutputWithPast,
    TokenClassifierOutput,
)
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import LossKwargs, auto_docstring, can_return_tuple, logging

# GemmaConfig is unmodified by us. It *is* modified by openpi's `transformers_replace`
# (it adds `use_adarms` / `adarms_cond_dim`), which openpi's own install applies; that
# is a dependency of openpi, not of this package's fork.
from transformers.models.gemma.configuration_gemma import GemmaConfig


logger = logging.get_logger(__name__)

# Fused denoise-loop kernels (RLinf). Optional: if triton is missing, too old,
# or the kill switches are set, every call site falls back to the plain eager
# op sequence below it, so this file still runs unmodified everywhere else.
try:
    from . import rlinf_fused_denoise as _FUSED_OPS

    if not _FUSED_OPS.HAVE_FUSED_DENOISE_OPS:
        _FUSED_OPS = None
except Exception:  # pragma: no cover - optional dependency
    _FUSED_OPS = None


class GemmaRMSNorm(nn.Module):
    def __init__(self, dim: int, eps: float = 1e-6, cond_dim: Optional[int] = None):
        super().__init__()
        self.eps = eps
        self.dim = dim
        self.cond_dim = cond_dim
        
        # Dense layer for adaptive normalization (if cond_dim is provided)
        if cond_dim is not None:
            #self.dense = nn.Linear(cond_dim, dim * 3, bias=True, dtype=torch.bfloat16)
            self.dense = nn.Linear(cond_dim, dim * 3, bias=True)
            # Initialize with zeros (matches source implementation)
            nn.init.zeros_(self.dense.weight)
        else:
            self.weight = nn.Parameter(torch.zeros(dim, dtype=torch.bfloat16))
            self.dense = None

    def _norm(self, x):
        # Compute variance in float32 (like the source implementation)
        var = torch.mean(torch.square(x.float()), dim=-1, keepdim=True)
        # Compute normalization in float32
        normed_inputs = x * torch.rsqrt(var + self.eps)
        return normed_inputs

    def forward(self, x, cond=None, mod=None):
        dtype = x.dtype  # original dtype, could be half-precision
        normed_inputs = self._norm(x)
        
        if self.dense is None or (cond is None and mod is None):
            # regular RMSNorm
            # scale by learned parameter in float32 (matches source implementation)
            normed_inputs = normed_inputs * (1.0 + self.weight.float())
            return normed_inputs.to(dtype), None  # return in original dtype with None gate

        # adaptive RMSNorm: driven either by a precomputed `mod` or by `cond` via self.dense.
        # `mod` alone is enough -- callers that supply it (the precomputed modulation table) may
        # legitimately pass cond=None, since the timestep conditioning would be dead work.
        if cond is not None and cond.shape[-1] != self.cond_dim:
            raise ValueError(f"Expected cond dimension {self.cond_dim}, got {cond.shape[-1]}")

        #self.dense.to(dtype=torch.bfloat16).to(dtype=torch.float32)
        # adaRMS projection: consume precomputed batched-GEMM slice `mod` when provided
        # (all per-norm dense(cond) projections coalesced into one GEMM upstream),
        # else fall back to this norm's own dense. Bit-identical: mod == self.dense(cond).
        modulation = mod if mod is not None else self.dense(cond)
        # Reshape modulation to broadcast properly: [batch, 1, features] for [batch, seq, features]
        if len(x.shape) == 3:  # [batch, seq, features]
            modulation = modulation.unsqueeze(1)
        
        scale, shift, gate = torch.chunk(modulation, 3, dim=-1)
        
        # Apply adaptive normalization: use model weight dtype to ensure compatibility
        # model_dtype = self.dense.weight.dtype  # Use the model's dtype (bfloat16)
        # scale = scale.to(model_dtype)
        # shift = shift.to(model_dtype)
        # gate = gate.to(model_dtype)
        # normed_inputs = normed_inputs.to(model_dtype)  # Convert normed_inputs to model dtype
        
        normed_inputs = normed_inputs * (1 + scale.to(torch.float32)) + shift.to(torch.float32)

        return normed_inputs.to(dtype), gate.to(dtype)

    def extra_repr(self):
        repr_str = f"{tuple(self.weight.shape)}, eps={self.eps}"
        if self.dense is not None:
            repr_str += f", adaptive=True, cond_dim={self.cond_dim}"
        return repr_str


class GemmaMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]
        # The fused gate/up+GeGLU kernel hard-codes tanh-approximated GELU.
        self._geglu_fusable = config.hidden_act in ("gelu_pytorch_tanh", "gelu_new")

    def forward(self, x):
        # Fused path: gelu_tanh(x @ Wg.T) * (x @ Wu.T) in ONE GEMM with two
        # accumulators over a shared A tile, replacing two GEMMs plus the
        # activation round-trip through HBM. Returns None when inapplicable.
        if _FUSED_OPS is not None and self._geglu_fusable:
            act = _FUSED_OPS.fused_gate_up_geglu(
                x, self.gate_proj.weight, self.up_proj.weight
            )
            if act is not None:
                return self.down_proj(act)
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


class GemmaRotaryEmbedding(nn.Module):
    def __init__(self, config: GemmaConfig, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and config.rope_scaling is not None:
            self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`, *optional*):
            Deprecated and unused.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def _gated_residual(x, y, gate):
    """
    Applies gated residual connection with optional gate parameter.
    
    Args:
        x: Input tensor (residual)
        y: Output tensor to be added
        gate: Optional gate tensor to modulate the addition
        
    Returns:
        x + y if gate is None, otherwise x + y * gate
    """
    if x is None and y is None:
        return None
    if x is None or y is None:
        return x if x is not None else y
    if gate is None:
        return x + y
    return x + y * gate


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs,
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


class GemmaAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: GemmaConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )
        # Fused QKV projection (built lazily by build_qkv_fused(); see below). Non-persistent:
        # derived from q/k/v_proj, which stay the checkpoint source of truth.
        self.register_buffer("qkv_fused_weight", None, persistent=False)
        self._qkv_split = None
        # Static KV buffers (prefix + suffix), primed once per predict by prime_kv_static().
        self.register_buffer("kv_static_k", None, persistent=False)
        self.register_buffer("kv_static_v", None, persistent=False)
        self._kv_prefix_len = 0

    def prime_kv_static(self, prefix_k, prefix_v, suffix_len):
        """Allocate (once) and fill the prefix half of this layer's static KV buffer.

        Call once per predict, after the prefix KV cache is built and before the denoise loop.
        The buffer is [B, kv_heads, prefix_len + suffix_len, head_dim]; the prefix part is
        written here, the suffix tail is overwritten by each denoise step in forward(). This
        replaces the per-step ``torch.cat`` that re-copied the whole prefix every step.

        Buffers are reallocated only when the shape changes, so their addresses stay stable
        across predicts -- required for CUDA-graph replay.
        """
        p = prefix_k.shape[2]
        want = (prefix_k.shape[0], prefix_k.shape[1], p + suffix_len, prefix_k.shape[3])
        if self.kv_static_k is None or tuple(self.kv_static_k.shape) != want:
            self.kv_static_k = torch.empty(want, dtype=prefix_k.dtype, device=prefix_k.device)
            self.kv_static_v = torch.empty(want, dtype=prefix_v.dtype, device=prefix_v.device)
        self.kv_static_k[:, :, :p, :].copy_(prefix_k)
        self.kv_static_v[:, :, :p, :].copy_(prefix_v)
        self._kv_prefix_len = p

    def build_qkv_fused(self):
        """Concatenate q/k/v_proj into ONE [q+k+v, hidden] weight so the three skinny GEMMs
        become a single wider one.

        At bs=1 (M=50) with MQA, k_proj/v_proj emit only 50x256 each -> triton tiles them into
        grid=8, i.e. 8 of ~110 SMs busy, running ~8x above their memory floor (launch/occupancy
        bound, ~10% of DRAM bandwidth). Fusing q(2048)+k(256)+v(256) into one 2560-wide output
        raises the tile count and cuts three launches to one. Mathematically identical: each
        output column is an independent dot product, so concatenating along N changes nothing.

        Only valid without bias (Gemma: attention_bias=False). Idempotent; safe to call twice.
        """
        if getattr(self, "qkv_fused_weight", None) is not None:
            return
        if self.q_proj.bias is not None or self.k_proj.bias is not None or self.v_proj.bias is not None:
            return  # biased variant not handled; keep the unfused path
        w = torch.cat([self.q_proj.weight, self.k_proj.weight, self.v_proj.weight], dim=0).contiguous()
        self.qkv_fused_weight = w
        self._qkv_split = (
            self.q_proj.weight.shape[0],
            self.k_proj.weight.shape[0],
            self.v_proj.weight.shape[0],
        )

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_value: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        use_cache: bool = False,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor], Optional[tuple[torch.Tensor]]]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)
        cos, sin = position_embeddings

        # Fused path: ONE kernel does the QKV projection and applies RoPE in its
        # epilogue, writing q into a [B, M, Hq, D] buffer (transposed below to
        # the exact strides the unfused view().transpose() produced) and the
        # rotated k / raw v straight into the static KV cache tail. Replaces the
        # QKV GEMM plus three pointwise RoPE/copy kernels. Only valid on the
        # denoise path (static KV primed, no DynamicCache update).
        if (
            _FUSED_OPS is not None
            and self.qkv_fused_weight is not None
            and past_key_value is not None
            and not use_cache
            and self.kv_static_k is not None
        ):
            fused_q = _FUSED_OPS.fused_qkv_rope_kv(
                hidden_states,
                self.qkv_fused_weight,
                cos,
                sin,
                self.kv_static_k,
                self.kv_static_v,
                self._kv_prefix_len,
                self.config.num_attention_heads,
                self.config.num_key_value_heads,
                self.head_dim,
            )
            if fused_q is not None:
                return self._attend_and_project(
                    fused_q.transpose(1, 2),
                    self.kv_static_k,
                    self.kv_static_v,
                    attention_mask,
                    input_shape,
                    **kwargs,
                )

        if self.qkv_fused_weight is not None:
            qkv = torch.nn.functional.linear(hidden_states, self.qkv_fused_weight)
            q_lin, k_lin, v_lin = torch.split(qkv, self._qkv_split, dim=-1)
            query_states = q_lin.view(hidden_shape).transpose(1, 2)
            key_states = k_lin.view(hidden_shape).transpose(1, 2)
            value_states = v_lin.view(hidden_shape).transpose(1, 2)
        else:
            query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
            key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
            value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        # Use cache if provided
        if past_key_value is not None:
            if use_cache:
                # sin and cos are specific to RoPE models; cache_position needed for the static cache
                cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
                key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
            elif self.kv_static_k is not None:
                # Static KV buffer: the prefix half was written once per predict (prime_kv_static);
                # each denoise step only writes the NEW suffix tokens into the tail slice. Avoids
                # re-copying the whole 968-token prefix every step, which torch.cat would do.
                # Same values as the cat, just without the redundant prefix copy.
                p = self._kv_prefix_len
                self.kv_static_k[:, :, p:, :].copy_(key_states)
                self.kv_static_v[:, :, p:, :].copy_(value_states)
                key_states = self.kv_static_k
                value_states = self.kv_static_v
            else:
                key_states = torch.cat([past_key_value[self.layer_idx][0], key_states], dim=2)
                value_states = torch.cat([past_key_value[self.layer_idx][1], value_states], dim=2)

        return self._attend_and_project(
            query_states, key_states, value_states, attention_mask, input_shape, **kwargs
        )

    def _attend_and_project(
        self, query_states, key_states, value_states, attention_mask, input_shape, **kwargs
    ):
        """Attention + output projection, shared by the fused and unfused QKV paths."""
        attention_interface: Callable = eager_attention_forward
        if self.config._attn_implementation != "eager":
            attention_interface = ALL_ATTENTION_FUNCTIONS[self.config._attn_implementation]

        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            **kwargs,
        )

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class GemmaDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: GemmaConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = GemmaAttention(config=config, layer_idx=layer_idx)

        self.mlp = GemmaMLP(config)
        cond_dim = getattr(config, 'adarms_cond_dim', None) if getattr(config, 'use_adarms', False) else None
        self.input_layernorm = GemmaRMSNorm(config.hidden_size, eps=config.rms_norm_eps, cond_dim=cond_dim)
        self.post_attention_layernorm = GemmaRMSNorm(config.hidden_size, eps=config.rms_norm_eps, cond_dim=cond_dim)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_value: Optional[Cache] = None,
        output_attentions: Optional[bool] = False,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,  # necessary, but kept here for BC
        adarms_cond: Optional[torch.Tensor] = None,
        adarms_mod: Optional[torch.Tensor] = None,  # precomputed [B,2,3072] modulation for this layer's 2 norms
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.FloatTensor, Optional[tuple[torch.FloatTensor, torch.FloatTensor]]]:
        residual = hidden_states
        hidden_states, gate = self.input_layernorm(
            hidden_states, adarms_cond, mod=(adarms_mod[:, 0, :] if adarms_mod is not None else None)
        )

        # Self Attention
        hidden_states, self_attn_weights = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_value=past_key_value,
            output_attentions=output_attentions,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = _gated_residual(residual, hidden_states, gate)

        # Fully Connected
        residual = hidden_states
        hidden_states, gate = self.post_attention_layernorm(
            hidden_states, adarms_cond, mod=(adarms_mod[:, 1, :] if adarms_mod is not None else None)
        )
        hidden_states = self.mlp(hidden_states)
        hidden_states = _gated_residual(residual, hidden_states, gate)

        outputs = (hidden_states,)
        if output_attentions:
            outputs += (self_attn_weights,)

        return outputs


@auto_docstring
class GemmaPreTrainedModel(PreTrainedModel):
    config_class = GemmaConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["GemmaDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn_3 = True
    _supports_flash_attn_2 = True
    _supports_sdpa = True
    _supports_flex_attn = True
    _supports_cache_class = True
    _supports_quantized_cache = True
    _supports_static_cache = True
    _supports_attention_backend = True

    def _init_weights(self, module):
        std = self.config.initializer_range
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, nn.Embedding):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.padding_idx is not None:
                module.weight.data[module.padding_idx].zero_()
        elif isinstance(module, GemmaRMSNorm):
            if hasattr(module, 'weight'):
                module.weight.data.fill_(1.0)


@auto_docstring
class GemmaModel(GemmaPreTrainedModel):
    def __init__(self, config: GemmaConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [GemmaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )

        cond_dim = getattr(config, 'adarms_cond_dim', None) if getattr(config, 'use_adarms', False) else None
        self.norm = GemmaRMSNorm(config.hidden_size, eps=config.rms_norm_eps, cond_dim=cond_dim)
        self.rotary_emb = GemmaRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # adaRMS batched projection: stacked weight/bias for all per-norm dense(cond) Linears,
        # built once by build_adarms_stack() before torch.compile. Non-persistent (derived from
        # the per-norm dense modules, which stay the checkpoint source of truth).
        self.register_buffer("adarms_Wstacked", None, persistent=False)      # [n*3072, cond_dim]
        self.register_buffer("adarms_bias_stacked", None, persistent=False)  # [n*3072]
        self._adarms_num = 0

        # Initialize weights and apply final processing
        self.post_init()

    def build_adarms_stack(self):
        """Coalesce the N per-norm adaRMS dense(cond) projections into one stacked GEMM.

        Enumerates the dense modules in the SAME order GemmaModel.forward consumes them
        (per layer: input_layernorm, post_attention_layernorm; then final self.norm) and
        stacks their weights/biases. Idempotent; no-op when the model has no adaRMS. Must run
        after weights are loaded + dtype-converted and before torch.compile traces forward.
        """
        norms = []
        for layer in self.layers:
            norms.append(layer.input_layernorm)
            norms.append(layer.post_attention_layernorm)
        norms.append(self.norm)
        norms = [n for n in norms if getattr(n, "dense", None) is not None]
        if not norms:
            return  # no adaRMS on this model (e.g. paligemma prefix)
        W = torch.cat([n.dense.weight for n in norms], dim=0).contiguous()  # [n*3072, cond_dim]
        b = torch.cat([n.dense.bias for n in norms], dim=0).contiguous()    # [n*3072]
        self.adarms_Wstacked = W
        self.adarms_bias_stacked = b
        self._adarms_num = len(norms)

    def build_qkv_fused(self):
        """Build the fused QKV weight on every attention layer (see GemmaAttention.build_qkv_fused)."""
        for layer in self.layers:
            attn = getattr(layer, "self_attn", None)
            if attn is not None and hasattr(attn, "build_qkv_fused"):
                attn.build_qkv_fused()

    def prime_kv_static(self, past_key_values, suffix_len):
        """Fill every layer's static KV buffer from a freshly built prefix cache.

        Call once per predict, before the denoise loop (see GemmaAttention.prime_kv_static).
        """
        for i, layer in enumerate(self.layers):
            attn = getattr(layer, "self_attn", None)
            if attn is None or not hasattr(attn, "prime_kv_static"):
                continue
            kv = past_key_values[i]
            attn.prime_kv_static(kv[0], kv[1], suffix_len)

    def clear_kv_static(self):
        """Disable the static-KV path (falls back to torch.cat). Used by code paths that do not
        prime it per predict, e.g. training with use_cache=True."""
        for layer in self.layers:
            attn = getattr(layer, "self_attn", None)
            if attn is not None:
                attn.kv_static_k = None
                attn.kv_static_v = None
                attn._kv_prefix_len = 0

    def refresh_derived_weights(self):
        """Re-derive the weight-derived tensors IN PLACE from the current weights.

        MUST be called after the weights change in place (e.g. an RL rollout weight sync):
        these tensors are copies computed FROM the weights, so they go stale even though the
        captured CUDA graph stays valid (the graph references weight ADDRESSES, which in-place
        updates preserve).

        Uses ``copy_`` rather than reallocating precisely so the derived tensors keep their
        addresses too -- a captured graph refers to these buffers as well, so replacing them
        with new tensors would make the graph read freed/stale memory.
        """
        if self.adarms_Wstacked is not None:
            norms = []
            for layer in self.layers:
                norms.append(layer.input_layernorm)
                norms.append(layer.post_attention_layernorm)
            norms.append(self.norm)
            norms = [n for n in norms if getattr(n, "dense", None) is not None]
            if norms:
                self.adarms_Wstacked.copy_(torch.cat([n.dense.weight for n in norms], dim=0))
                self.adarms_bias_stacked.copy_(torch.cat([n.dense.bias for n in norms], dim=0))
        for layer in self.layers:
            attn = getattr(layer, "self_attn", None)
            if attn is not None and getattr(attn, "qkv_fused_weight", None) is not None:
                attn.qkv_fused_weight.copy_(
                    torch.cat([attn.q_proj.weight, attn.k_proj.weight, attn.v_proj.weight], dim=0)
                )

    def get_input_embeddings(self):
        return self.embed_tokens

    def set_input_embeddings(self, value):
        self.embed_tokens = value

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        adarms_cond: Optional[torch.Tensor] = None,
        adarms_mod: Optional[torch.Tensor] = None,  # precomputed [B, n_norm, 3072] modulation table slice (cache path)
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> BaseModelOutputWithPast:
        """
        adarms_cond (`torch.Tensor` of shape `(batch_size, cond_dim)`, *optional*):
            Condition for ADARMS.
        """
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        use_cache = use_cache if use_cache is not None else self.config.use_cache

        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if self.gradient_checkpointing and self.training and use_cache:
            logger.warning_once(
                "`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`."
            )
            use_cache = False

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache()

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        causal_mask = create_causal_mask(
            config=self.config,
            input_embeds=inputs_embeds,
            attention_mask=attention_mask,
            cache_position=cache_position,
            past_key_values=past_key_values,
            position_ids=position_ids,
        )

        # embed positions
        hidden_states = inputs_embeds
        # Convert to bfloat16 if the first layer uses bfloat16
        if len(self.layers) > 0 and self.layers[0].self_attn.q_proj.weight.dtype == torch.bfloat16:
            hidden_states = hidden_states.to(torch.bfloat16)

        # create position embeddings to be shared across the decoder layers.
        # The caller may hand in a precomputed (cos, sin) pair: the rotary table depends only
        # on ``position_ids``, which is fixed for the whole denoise loop, so the sampling loop
        # builds it once per predict instead of once per Euler step (see
        # ``OpenPi0Inference._build_step_invariants``). Same values, so the layers below cannot
        # tell the difference.
        if position_embeddings is None:
            position_embeddings = self.rotary_emb(hidden_states, position_ids)

        # normalized
        # Gemma downcasts the below to float16, causing sqrt(3072)=55.4256 to become 55.5
        # See https://github.com/huggingface/transformers/pull/29402
        normalizer = torch.tensor(self.config.hidden_size**0.5, dtype=hidden_states.dtype)
        #hidden_states = hidden_states * normalizer

        # adaRMS modulation. CACHE path: use the precomputed [B, n_norm, 3072] table slice passed
        # from the sampling loop (the 37 dense(cond) projections are input-independent given the
        # fixed timestep schedule, so they are precomputed once and indexed here -> no per-step
        # weight read at all). FALLBACK: if only cond is given, compute the batched projection.
        if adarms_mod is not None:
            adarms_mod_all = adarms_mod
        elif adarms_cond is not None and self.adarms_Wstacked is not None:
            adarms_mod_all = torch.nn.functional.linear(
                adarms_cond, self.adarms_Wstacked, self.adarms_bias_stacked
            ).view(adarms_cond.shape[0], self._adarms_num, -1)  # [B, n, 3072]
        else:
            adarms_mod_all = None

        # decoder layers
        all_hidden_states = () if output_hidden_states else None
        all_self_attns = () if output_attentions else None

        for i, decoder_layer in enumerate(self.layers[: self.config.num_hidden_layers]):
            if output_hidden_states:
                all_hidden_states += (hidden_states,)

            layer_outputs = decoder_layer(
                hidden_states,
                attention_mask=causal_mask,
                position_ids=position_ids,
                past_key_value=past_key_values,
                output_attentions=output_attentions,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                adarms_cond=adarms_cond,
                adarms_mod=(adarms_mod_all[:, 2 * i:2 * i + 2, :] if adarms_mod_all is not None else None),
                **kwargs,
            )

            hidden_states = layer_outputs[0]

            if output_attentions:
                all_self_attns += (layer_outputs[1],)

        final_mod = adarms_mod_all[:, self._adarms_num - 1, :] if adarms_mod_all is not None else None
        hidden_states, _ = self.norm(hidden_states, adarms_cond, mod=final_mod)

        # add hidden states from the last decoder layer
        if output_hidden_states:
            all_hidden_states += (hidden_states,)

        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
            hidden_states=all_hidden_states,
            attentions=all_self_attns,
        )


class KwargsForCausalLM(FlashAttentionKwargs, LossKwargs): ...


@auto_docstring
class GemmaForCausalLM(GemmaPreTrainedModel, GenerationMixin):
    _tied_weights_keys = ["lm_head.weight"]
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = GemmaModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.model.embed_tokens

    def set_input_embeddings(self, value):
        self.model.embed_tokens = value

    def get_output_embeddings(self):
        return self.lm_head

    def set_output_embeddings(self, new_embeddings):
        self.lm_head = new_embeddings

    def set_decoder(self, decoder):
        self.model = decoder

    def get_decoder(self):
        return self.model

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        adarms_cond: Optional[torch.Tensor] = None,
        **kwargs: Unpack[KwargsForCausalLM],
    ) -> CausalLMOutputWithPast:
        r"""
        labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
            Labels for computing the masked language modeling loss. Indices should either be in `[0, ...,
            config.vocab_size]` or -100 (see `input_ids` docstring). Tokens with indices set to `-100` are ignored
            (masked), the loss is only computed for the tokens with labels in `[0, ..., config.vocab_size]`.

        adarms_cond (`torch.Tensor` of shape `(batch_size, cond_dim)`, *optional*):
            Condition for ADARMS.

        Example:

        ```python
        >>> from transformers import AutoTokenizer, GemmaForCausalLM

        >>> model = GemmaForCausalLM.from_pretrained("google/gemma-7b")
        >>> tokenizer = AutoTokenizer.from_pretrained("google/gemma-7b")

        >>> prompt = "What is your favorite condiment?"
        >>> inputs = tokenizer(prompt, return_tensors="pt")

        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "What is your favorite condiment?"
        ```"""
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )

        # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            cache_position=cache_position,
            adarms_cond=adarms_cond,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )


@auto_docstring(
    custom_intro="""
    The Gemma Model transformer with a sequence classification head on top (linear layer).

    [`GemmaForSequenceClassification`] uses the last token in order to do the classification, as other causal models
    (e.g. GPT-2) do.

    Since it does classification on the last token, it requires to know the position of the last token. If a
    `pad_token_id` is defined in the configuration, it finds the last token that is not a padding token in each row. If
    no `pad_token_id` is defined, it simply takes the last value in each row of the batch. Since it cannot guess the
    padding tokens when `inputs_embeds` are passed instead of `input_ids`, it does the same (take the last value in
    each row of the batch).
    """
)
class GemmaForSequenceClassification(GemmaPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.model = GemmaModel(config)
        self.score = nn.Linear(config.hidden_size, self.num_labels, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.model.embed_tokens

    def set_input_embeddings(self, value):
        self.model.embed_tokens = value

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        adarms_cond: Optional[torch.Tensor] = None,
    ) -> SequenceClassifierOutputWithPast:
        r"""
        labels (`torch.LongTensor` of shape `(batch_size,)`, *optional*):
            Labels for computing the sequence classification/regression loss. Indices should be in `[0, ...,
            config.num_labels - 1]`. If `config.num_labels == 1` a regression loss is computed (Mean-Square loss), If
            `config.num_labels > 1` a classification loss is computed (Cross-Entropy).

        adarms_cond (`torch.Tensor` of shape `(batch_size, cond_dim)`, *optional*):
            Condition for ADARMS.
        """

        transformer_outputs: BaseModelOutputWithPast = self.model(
            input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            adarms_cond=adarms_cond,
        )
        hidden_states = transformer_outputs.last_hidden_state
        logits = self.score(hidden_states)

        if input_ids is not None:
            batch_size = input_ids.shape[0]
        else:
            batch_size = inputs_embeds.shape[0]

        if self.config.pad_token_id is None and batch_size != 1:
            raise ValueError("Cannot handle batch sizes > 1 if no padding token is defined.")
        if self.config.pad_token_id is None:
            last_non_pad_token = -1
        elif input_ids is not None:
            # To handle both left- and right- padding, we take the rightmost token that is not equal to pad_token_id
            non_pad_mask = (input_ids != self.config.pad_token_id).to(logits.device, torch.int32)
            token_indices = torch.arange(input_ids.shape[-1], device=logits.device, dtype=torch.int32)
            last_non_pad_token = (token_indices * non_pad_mask).argmax(-1)
        else:
            last_non_pad_token = -1
            logger.warning_once(
                f"{self.__class__.__name__} will not detect padding tokens in `inputs_embeds`. Results may be "
                "unexpected if using padding tokens in conjunction with `inputs_embeds.`"
            )

        pooled_logits = logits[torch.arange(batch_size, device=logits.device), last_non_pad_token]

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, pooled_logits=pooled_logits, config=self.config)

        return SequenceClassifierOutputWithPast(
            loss=loss,
            logits=pooled_logits,
            past_key_values=transformer_outputs.past_key_values,
            hidden_states=transformer_outputs.hidden_states,
            attentions=transformer_outputs.attentions,
        )


@auto_docstring
class GemmaForTokenClassification(GemmaPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.model = GemmaModel(config)
        if getattr(config, "classifier_dropout", None) is not None:
            classifier_dropout = config.classifier_dropout
        elif getattr(config, "hidden_dropout", None) is not None:
            classifier_dropout = config.hidden_dropout
        else:
            classifier_dropout = 0.1
        self.dropout = nn.Dropout(classifier_dropout)
        self.score = nn.Linear(config.hidden_size, config.num_labels)

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.model.embed_tokens

    def set_input_embeddings(self, value):
        self.model.embed_tokens = value

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        adarms_cond: Optional[torch.Tensor] = None,
    ) -> TokenClassifierOutput:
        r"""
        labels (`torch.LongTensor` of shape `(batch_size,)`, *optional*):
            Labels for computing the sequence classification/regression loss. Indices should be in `[0, ...,
            config.num_labels - 1]`. If `config.num_labels == 1` a regression loss is computed (Mean-Square loss), If
            `config.num_labels > 1` a classification loss is computed (Cross-Entropy).

        adarms_cond (`torch.Tensor` of shape `(batch_size, cond_dim)`, *optional*):
            Condition for ADARMS.
        """

        outputs: BaseModelOutputWithPast = self.model(
            input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            adarms_cond=adarms_cond,
        )
        sequence_output = outputs.last_hidden_state
        sequence_output = self.dropout(sequence_output)
        logits = self.score(sequence_output)

        loss = None
        if labels is not None:
            loss = self.loss_function(logits, labels, self.config)

        return TokenClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )


__all__ = [
    "GemmaModel",
    "GemmaForCausalLM",
    "GemmaForSequenceClassification",
    "GemmaForTokenClassification",
    "GemmaPreTrainedModel",
]
